"""
STATUM1 Website Generator — produces a complete static website for GitHub Pages.

Pages generated:
  index.html   — home page with email capture and featured content
  books.html   — full product catalogue grouped by category
  blog.html    — SEO article index
  about.html   — about Gareth Price and Sophia Melrose

Blog articles are generated separately by engines/marketing/seo_writer.py.
Lead magnet PDF is generated by engines/marketing/email_list.py.

Deployment: push dashboard/website/ to gh-pages branch via GitHub Actions.

Run manually:   python -m dashboard.website.generate
Scheduler call: _job_website_generate() in core/scheduler.py (daily 06:00 UTC)
"""

import html
import json
import logging
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

logger     = logging.getLogger(__name__)
OUTPUT_DIR = Path(__file__).parent
BLOG_DIR   = OUTPUT_DIR / "blog"
DB_PATH    = Path("database") / "statum1_intelligence.db"
MKTG_DB    = Path("database") / "statum1_marketing.db"
STORE_URL  = "https://middleton26.gumroad.com"
SITE_URL   = os.environ.get("SITE_URL", "https://statum1.co.uk")
SITEMAP_BASE = os.environ.get("SITEMAP_BASE", "https://tempest1953.github.io/statum1-website")
GA_ID      = os.environ.get("GOOGLE_ANALYTICS_ID", "GA_MEASUREMENT_ID")

# Mailchimp embedded form action — set this in .env after getting your embed URL
# from Mailchimp → Audience → Signup forms → Embedded forms
MAILCHIMP_FORM = os.environ.get(
    "MAILCHIMP_FORM_ACTION",
    "https://YOUR_MC_DOMAIN.us1.list-manage.com/subscribe/post?u=XXXXXXXX&amp;id=XXXXXXXX",
)


# ── Shared CSS ─────────────────────────────────────────────────────────────────

_BASE_CSS = """
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Georgia,serif;
     background:#fafafa;color:#1a1a2e;line-height:1.7}
a{color:#1a1a2e;text-decoration:none}
img{max-width:100%;height:auto}

/* ── Navigation ── */
.site-nav{display:flex;align-items:center;justify-content:space-between;
          padding:14px 28px;background:#1a1a2e;position:sticky;top:0;z-index:100}
.nav-logo{color:#c9a84c;font-weight:700;font-size:1.05rem;letter-spacing:-0.3px}
.nav-links a{color:#ccc;margin-left:22px;font-size:0.88rem;transition:color .15s}
.nav-links a:hover,.nav-links a.active{color:#fff}

/* ── Sections ── */
.container{max-width:1080px;margin:0 auto;padding:0 24px}
section{padding:60px 0}
h2.section-title{font-size:1.7rem;margin-bottom:8px;color:#1a1a2e}
.section-sub{color:#666;margin-bottom:36px;font-size:1rem}

/* ── Hero ── */
.hero{background:#1a1a2e;color:#fff;padding:80px 24px;text-align:center}
.hero h1{font-size:2.6rem;line-height:1.2;max-width:700px;margin:0 auto 16px;
         letter-spacing:-0.5px}
.hero p{color:#a0a8c0;font-size:1.1rem;max-width:580px;margin:0 auto 32px}
.hero-gold{color:#c9a84c}

/* ── Email capture ── */
.email-box{background:rgba(255,255,255,.06);border:1px solid rgba(201,168,76,.4);
           border-radius:12px;padding:32px;max-width:520px;margin:0 auto;text-align:left}
.email-box h3{color:#c9a84c;font-size:1.1rem;margin-bottom:6px}
.email-box p{color:#b0b8c8;font-size:0.88rem;margin-bottom:16px}
.email-form{display:flex;gap:10px;flex-wrap:wrap}
.email-form input[type=email]{flex:1;min-width:200px;padding:12px 16px;
  border-radius:6px;border:none;font-size:0.92rem;outline:none}
.email-form button{background:#c9a84c;color:#1a1a2e;border:none;padding:12px 22px;
  border-radius:6px;font-weight:700;cursor:pointer;font-size:0.92rem;transition:background .2s}
.email-form button:hover{background:#b8934a}
.email-note{color:#778;font-size:0.75rem;margin-top:10px}
.mc-success{display:none;color:#4ade80;font-size:0.88rem;margin-top:10px}

/* ── Product cards ── */
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:22px}
.card{background:#fff;border-radius:10px;padding:22px;position:relative;
      box-shadow:0 2px 8px rgba(0,0,0,.07);transition:transform .2s,box-shadow .2s;
      display:flex;flex-direction:column}
.card:hover{transform:translateY(-3px);box-shadow:0 6px 20px rgba(0,0,0,.11)}
.card-badge{position:absolute;top:14px;right:14px;border-radius:20px;
            padding:2px 10px;font-size:0.72rem;color:#fff;font-weight:600}
.card-cat{font-size:0.73rem;color:#999;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}
.card h3{font-size:1rem;line-height:1.3;margin-bottom:8px}
.card h3 a:hover{text-decoration:underline}
.card p{font-size:0.84rem;color:#555;flex:1;margin-bottom:14px}
.card-foot{display:flex;align-items:center;justify-content:space-between;
           border-top:1px solid #f0f0f0;padding-top:12px;margin-top:auto}
.price{font-weight:700;color:#1a1a2e;font-size:1rem}
.btn{background:#1a1a2e;color:#fff;padding:8px 16px;border-radius:6px;
     font-size:0.82rem;transition:background .2s}
.btn:hover{background:#2d2d5e}
.btn-gold{background:#c9a84c;color:#1a1a2e}
.btn-gold:hover{background:#b8934a}

/* ── Blog cards ── */
.blog-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:22px}
.blog-card{background:#fff;border-radius:10px;padding:22px;
           box-shadow:0 2px 8px rgba(0,0,0,.07);transition:box-shadow .2s}
.blog-card:hover{box-shadow:0 6px 18px rgba(0,0,0,.11)}
.blog-cat{font-size:0.72rem;text-transform:uppercase;letter-spacing:.5px;color:#c9a84c;margin-bottom:6px}
.blog-title{font-size:1rem;line-height:1.35;margin-bottom:8px}
.blog-title a:hover{text-decoration:underline}
.blog-date{font-size:0.75rem;color:#aaa}

/* ── About ── */
.about-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px}
.author-card{background:#fff;border-radius:10px;padding:32px;
             box-shadow:0 2px 8px rgba(0,0,0,.07)}
.author-card h3{font-size:1.25rem;margin-bottom:4px}
.author-role{font-size:0.82rem;color:#c9a84c;font-weight:600;
             text-transform:uppercase;letter-spacing:.5px;margin-bottom:14px}
.author-card p{font-size:0.9rem;color:#444;line-height:1.7;margin-bottom:12px}

/* ── Footer ── */
footer{text-align:center;padding:36px 24px;color:#aaa;font-size:0.8rem;
       border-top:1px solid #e9ecef;background:#fff;margin-top:40px}
footer a{color:#888}

/* ── Responsive ── */
@media(max-width:680px){
  .hero h1{font-size:1.8rem}
  .about-grid{grid-template-columns:1fr}
  .site-nav{flex-direction:column;gap:10px;padding:14px}
  .nav-links a{margin-left:12px}
}
"""

_GA_SNIPPET = f"""
  <script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script>
  <script>
    window.dataLayer=window.dataLayer||[];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js',new Date());gtag('config','{GA_ID}');
  </script>"""


def _nav(active: str = "home") -> str:
    def link(href, page, label):
        cls = ' class="active"' if page == active else ""
        return f'<a href="{href}"{cls}>{label}</a>'
    return f"""<nav class="site-nav">
  <a href="./index.html" class="nav-logo">Middleton &amp; Price</a>
  <div class="nav-links">
    {link("./index.html","home","Home")}
    {link("./books.html","books","Books")}
    {link("./blog.html","blog","Blog")}
    {link("./about.html","about","About")}
  </div>
</nav>"""


def _footer() -> str:
    year = datetime.now().year
    return f"""<footer>
  <p>&copy; {year} Middleton &amp; Price Publishing &middot;
     <a href="{STORE_URL}">Gumroad Store</a> &middot;
     Not financial or personal advice
  </p>
</footer>"""


def _head(title: str, description: str, canonical: str, page: str = "website") -> str:
    schema = json.dumps({
        "@context": "https://schema.org",
        "@type":    "WebSite",
        "name":     "Middleton & Price",
        "url":      SITE_URL,
    })
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(description)}"/>
  <meta name="robots" content="index, follow"/>
  <meta name="google-site-verification" content="XXBjxcAy67UUSUtduBjIAr5rPdw15Xn3549xcbSfLvA"/>
  <link rel="canonical" href="{canonical}"/>
  <meta property="og:title"       content="{html.escape(title)}"/>
  <meta property="og:description" content="{html.escape(description)}"/>
  <meta property="og:type"        content="{page}"/>
  <meta property="og:url"         content="{canonical}"/>
  <meta property="og:site_name"   content="Middleton &amp; Price"/>
  <script type="application/ld+json">{schema}</script>
  {_GA_SNIPPET}
  <style>{_BASE_CSS}</style>
</head>
<body>"""


# ── Product data ───────────────────────────────────────────────────────────────

_CATEGORY_ORDER = [
    "Relationships", "Vanity", "Dark_Psych", "Anti_Aging",
    "Wealth_Status", "Ai_Professionals", "Geopolitical",
    "Investing", "Tech", "Macro", "Crypto", "Fx", "Equities",
    "Commodities", "Banking", "General",
]

_CATEGORY_LABELS = {
    "Relationships":   "Relationships & Love",
    "Vanity":          "Confidence & Presence",
    "Dark_Psych":      "Psychology & Influence",
    "Anti_Aging":      "Health & Longevity",
    "Wealth_Status":   "Success & Mindset",
    "Ai_Professionals":"AI for Professionals",
    "Geopolitical":    "Geopolitical Investing",
    "Tech":            "Technology Investing",
    "Crypto":          "Crypto Investing",
    "Macro":           "Macro & Economics",
    "Fx":              "Forex",
    "Equities":        "Equities",
    "Commodities":     "Commodities",
    "Banking":         "Banking & Finance",
    "General":         "General",
}

_BADGE_COLORS = {
    "published": "#2ecc71",
    "draft":     "#3498db",
    "ready":     "#3498db",
}


def _load_products() -> list[dict]:
    if not DB_PATH.exists():
        return []
    products: list[dict] = []
    with sqlite3.connect(DB_PATH) as con:
        con.row_factory = sqlite3.Row
        try:
            for r in con.execute(
                "SELECT title, product_type, price_cents, trend_topic, "
                "description, listing_url, status, created_at "
                "FROM muse_products "
                "WHERE status IN ('draft','published','ready') "
                "ORDER BY created_at DESC"
            ).fetchall():
                topic = (r["trend_topic"] or "General")
                products.append({
                    "title":       r["title"],
                    "type":        r["product_type"].replace("_", " ").title(),
                    "price":       r["price_cents"] / 100,
                    "topic":       topic,
                    "description": (r["description"] or "")[:280],
                    "url":         r["listing_url"] or STORE_URL,
                    "status":      r["status"],
                    "source":      "MUSE",
                    "asin":        "",
                })
        except Exception:
            pass
        try:
            for r in con.execute(
                "SELECT title, description, listing_url, price_cents, status "
                "FROM lens_reports WHERE status IN ('draft','published') "
                "ORDER BY created_at DESC"
            ).fetchall():
                products.append({
                    "title":       r["title"],
                    "type":        "Market Report",
                    "price":       (r["price_cents"] or 0) / 100,
                    "topic":       "Geopolitical",
                    "description": (r["description"] or "")[:280],
                    "url":         r["listing_url"] or STORE_URL,
                    "status":      r["status"],
                    "source":      "LENS",
                    "asin":        "",
                })
        except Exception:
            pass

    # Load ASINs from book_registry.json if present
    registry_path = Path("database") / "book_registry.json"
    registry: dict = {}
    if registry_path.exists():
        try:
            registry = json.loads(registry_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    for p in products:
        reg = registry.get(p["title"], {})
        if reg.get("asin"):
            p["asin"] = reg["asin"]

    return products


def _product_card(p: dict, idx: int, badge: bool = True) -> str:
    badge_color = _BADGE_COLORS.get(p["status"], "#3498db")
    badge_html  = (f'<div class="card-badge" style="background:{badge_color}">'
                   f'{"Published" if p["status"] == "published" else "New"}</div>'
                   if badge else "")
    cat_label   = _CATEGORY_LABELS.get(p["topic"], p["topic"].replace("_", " ").title())
    url         = html.escape(p["url"])
    title       = html.escape(p["title"])
    desc        = html.escape(p["description"])
    price_str   = f"£{p['price']:.2f}"

    amazon_btn = ""
    if p.get("asin"):
        asin_url = html.escape(f"https://www.amazon.co.uk/dp/{p['asin']}")
        amazon_btn = (f'<a href="{asin_url}" class="btn" style="margin-left:8px;background:#f90;color:#000" '
                      f'rel="noopener" target="_blank">Amazon</a>')

    return f"""
<article class="card" itemscope itemtype="https://schema.org/Book">
  {badge_html}
  <div class="card-cat">{html.escape(cat_label)}</div>
  <h3 itemprop="name"><a href="{url}" rel="noopener" target="_blank">{title}</a></h3>
  <p itemprop="description">{desc}{"…" if len(p["description"]) >= 280 else ""}</p>
  <div class="card-foot">
    <span class="price" itemprop="offers" itemscope itemtype="https://schema.org/Offer">
      <span itemprop="price" content="{p['price']:.2f}">{price_str}</span>
      <meta itemprop="priceCurrency" content="GBP"/>
    </span>
    <div>
      <a href="{url}" class="btn btn-gold" rel="noopener" target="_blank">Buy</a>
      {amazon_btn}
    </div>
  </div>
</article>"""


# ── Blog article index ─────────────────────────────────────────────────────────

def _load_blog_articles() -> list[dict]:
    """Load written articles from seo_articles table."""
    articles = []
    if not MKTG_DB.exists():
        return articles
    try:
        with sqlite3.connect(MKTG_DB) as con:
            rows = con.execute(
                "SELECT slug, keyword, category, title, created_at "
                "FROM seo_articles ORDER BY created_at DESC"
            ).fetchall()
        for r in rows:
            slug     = r[0]
            html_path = BLOG_DIR / f"{slug}.html"
            if not html_path.exists():
                continue
            # Read meta_description from file quickly
            meta_desc = ""
            try:
                text = html_path.read_text(encoding="utf-8", errors="ignore")
                import re
                m = re.search(r'<meta name="description" content="([^"]*)"', text)
                if m:
                    meta_desc = m.group(1)
            except Exception:
                pass
            articles.append({
                "slug":     slug,
                "keyword":  r[1],
                "category": (r[2] or "").replace("_", " ").title(),
                "title":    r[3] or r[1].title(),
                "date":     r[4][:10] if r[4] else "",
                "meta":     meta_desc[:120],
            })
    except Exception:
        pass
    return articles


# ── Page generators ────────────────────────────────────────────────────────────

def generate_home() -> Path:
    """Generate index.html — home page with email capture, featured books, recent blog."""
    products = _load_products()
    articles = _load_blog_articles()

    # Select one featured book per category (first match, max 6)
    featured: list[dict] = []
    seen_cats: set = set()
    for p in products:
        cat = p["topic"]
        if cat not in seen_cats and len(featured) < 6:
            featured.append(p)
            seen_cats.add(cat)

    featured_cards = "\n".join(_product_card(p, i, badge=False) for i, p in enumerate(featured))
    all_count = len(products)
    recent_blog = articles[:3]

    recent_html = ""
    for a in recent_blog:
        recent_html += f"""
<article class="blog-card">
  <div class="blog-cat">{html.escape(a["category"])}</div>
  <h3 class="blog-title"><a href="./blog/{html.escape(a["slug"])}.html">{html.escape(a["title"])}</a></h3>
  <p style="font-size:0.84rem;color:#555;margin-bottom:8px">{html.escape(a["meta"])}</p>
  <span class="blog-date">{a["date"]}</span>
</article>"""

    blog_section = f"""
<section style="background:#f0f0f5;padding:60px 0">
  <div class="container">
    <h2 class="section-title">From the Blog</h2>
    <p class="section-sub">Practical advice on relationships, psychology, and personal growth</p>
    <div class="blog-grid">{recent_html}</div>
    <p style="text-align:center;margin-top:28px">
      <a href="./blog.html" class="btn">Read All Articles</a>
    </p>
  </div>
</section>""" if recent_blog else ""

    page = (
        _head(
            "Middleton & Price — Books That Change the Way You Think",
            "Practical books on relationships, psychology, confidence, and smart investing. "
            "Evidence-based, beautifully written, immediately actionable.",
            SITE_URL,
        )
        + _nav("home")
        + f"""
<main>
  <!-- Hero -->
  <section class="hero">
    <h1>Books That Change the<br/><span class="hero-gold">Way You Think</span></h1>
    <p>Evidence-based guides on relationships, psychology, confidence, and investing.
       Written for people who want clarity, not clichés.</p>

    <!-- Email capture -->
    <div class="email-box">
      <h3>Get your FREE guide</h3>
      <p>5 Signs He's Pulling Away and What To Do About It — instantly delivered</p>
      <form class="email-form" action="{MAILCHIMP_FORM}" method="post" target="_blank"
            novalidate id="mc-form">
        <input type="email" name="EMAIL" placeholder="Your email address" required
               aria-label="Email address"/>
        <!-- Mailchimp anti-spam honeypot — do not remove -->
        <div style="position:absolute;left:-5000px" aria-hidden="true">
          <input type="text" name="b_placeholder" tabindex="-1" value=""/>
        </div>
        <button type="submit">Get Free Guide</button>
      </form>
      <p class="email-note">No spam. Unsubscribe any time. One email per week maximum.</p>
    </div>
  </section>

  <!-- Featured books -->
  <section>
    <div class="container">
      <h2 class="section-title">Featured Books</h2>
      <p class="section-sub">A selection from our library of {all_count} titles</p>
      <div class="grid">{featured_cards}</div>
      <p style="text-align:center;margin-top:32px">
        <a href="./books.html" class="btn btn-gold">Browse All {all_count} Books &rarr;</a>
      </p>
    </div>
  </section>

  {blog_section}
</main>
"""
        + _footer()
        + "\n</body>\n</html>"
    )

    out = OUTPUT_DIR / "index.html"
    out.write_text(page, encoding="utf-8")
    logger.info("[website] index.html — %d products, %d blog articles", all_count, len(articles))
    return out


def generate_books() -> Path:
    """Generate books.html — full catalogue grouped by category."""
    products  = _load_products()
    now_str   = datetime.now(timezone.utc).strftime("%d %B %Y")

    # Group by topic
    grouped: dict[str, list[dict]] = {}
    for p in products:
        grouped.setdefault(p["topic"], []).append(p)

    sections_html = ""
    for cat in _CATEGORY_ORDER + sorted(grouped.keys()):
        if cat not in grouped:
            continue
        label = _CATEGORY_LABELS.get(cat, cat.replace("_", " ").title())
        cards = "\n".join(_product_card(p, i) for i, p in enumerate(grouped[cat]))
        sections_html += f"""
<section id="{cat.lower()}" style="padding:40px 0 20px">
  <div class="container">
    <h2 style="font-size:1.3rem;margin-bottom:20px;color:#1a1a2e;
               border-left:4px solid #c9a84c;padding-left:12px">{html.escape(label)}</h2>
    <div class="grid">{cards}</div>
  </div>
</section>"""

    page = (
        _head(
            f"All Books — Middleton & Price ({len(products)} titles)",
            "Browse our full library of practical guides on relationships, psychology, confidence, "
            "investing, and AI for professionals. Available on Gumroad and Amazon.",
            f"{SITE_URL}/books.html",
        )
        + _nav("books")
        + f"""
<main>
  <div style="background:#1a1a2e;color:#fff;padding:40px 24px;text-align:center">
    <h1 style="font-size:2rem;margin-bottom:8px">The Library</h1>
    <p style="color:#a0a8c0">{len(products)} titles &middot; Updated {now_str}</p>
  </div>
  {sections_html}
</main>
"""
        + _footer()
        + "\n</body>\n</html>"
    )

    out = OUTPUT_DIR / "books.html"
    out.write_text(page, encoding="utf-8")
    logger.info("[website] books.html — %d products", len(products))
    return out


def generate_blog_index() -> Path:
    """Generate blog.html — index of all SEO articles."""
    articles = _load_blog_articles()

    if articles:
        cards_html = "".join(f"""
<article class="blog-card">
  <div class="blog-cat">{html.escape(a["category"])}</div>
  <h2 class="blog-title">
    <a href="./blog/{html.escape(a["slug"])}.html">{html.escape(a["title"])}</a>
  </h2>
  <p style="font-size:0.84rem;color:#555;margin:6px 0 10px">{html.escape(a["meta"])}</p>
  <span class="blog-date">{a["date"]}</span>
</article>""" for a in articles)
        body = f'<div class="blog-grid">{cards_html}</div>'
    else:
        body = """
<div style="text-align:center;padding:60px 0;color:#888">
  <p style="font-size:1.1rem">Articles coming soon — check back shortly.</p>
  <p style="margin-top:8px;font-size:0.9rem">
    New articles are published every Tuesday and Thursday.
  </p>
</div>"""

    page = (
        _head(
            "Blog — Middleton & Price | Relationships, Psychology & Investing",
            "Practical articles on attachment, body language, confidence, and smart money. "
            "New articles every week, built around our book topics.",
            f"{SITE_URL}/blog.html",
        )
        + _nav("blog")
        + f"""
<main>
  <div style="background:#1a1a2e;color:#fff;padding:40px 24px;text-align:center">
    <h1 style="font-size:2rem;margin-bottom:8px">The Blog</h1>
    <p style="color:#a0a8c0">Practical advice published every Tuesday and Thursday</p>
  </div>
  <section style="padding:50px 0">
    <div class="container">{body}</div>
  </section>
</main>
"""
        + _footer()
        + "\n</body>\n</html>"
    )

    out = OUTPUT_DIR / "blog.html"
    out.write_text(page, encoding="utf-8")
    logger.info("[website] blog.html — %d articles", len(articles))
    return out


def generate_about() -> Path:
    """Generate about.html — about Gareth Price and Sophia Melrose."""
    page = (
        _head(
            "About — Middleton & Price",
            "Middleton & Price is an independent publisher of practical non-fiction guides "
            "on relationships, psychology, confidence, and investing.",
            f"{SITE_URL}/about.html",
        )
        + _nav("about")
        + """
<main>
  <div style="background:#1a1a2e;color:#fff;padding:40px 24px;text-align:center">
    <h1 style="font-size:2rem;margin-bottom:8px">About Us</h1>
    <p style="color:#a0a8c0">Independent publishers of evidence-based practical guides</p>
  </div>

  <section>
    <div class="container">
      <p style="max-width:680px;margin:0 auto 40px;font-size:1rem;color:#444;line-height:1.8;text-align:center">
        Middleton &amp; Price was built around a single belief: that well-written,
        genuinely researched books change how people think and act. Every title
        in our library goes through the same test — does it contain actionable
        insight that makes a measurable difference to the reader?
      </p>

      <div class="about-grid">

        <div class="author-card" itemscope itemtype="https://schema.org/Person">
          <h3 itemprop="name">Gareth Price</h3>
          <div class="author-role">Publisher &amp; Technology Author</div>
          <p itemprop="description">
            Gareth Price is an entrepreneur and systems thinker with a background in
            technology and data-driven decision making. He founded Middleton &amp; Price
            to bring together practical non-fiction across several categories — all united
            by the same principle: research first, opinion second.
          </p>
          <p>
            Gareth writes primarily on investing, geopolitics, AI for business, and
            the psychology of performance. His books are used by business owners,
            investors, and professionals who want frameworks rather than motivation.
          </p>
          <p>
            When not writing, he builds the data infrastructure that keeps Middleton
            &amp; Price's research current — monitoring markets, geopolitical shifts,
            and emerging trends to ensure every title remains relevant.
          </p>
        </div>

        <div class="author-card" itemscope itemtype="https://schema.org/Person">
          <h3 itemprop="name">Sophia Melrose</h3>
          <div class="author-role">Relationships &amp; Psychology Author</div>
          <p itemprop="description">
            Sophia Melrose writes about the psychology of human connection — attachment
            theory, body language, manipulation, confidence, and the often baffling
            dynamics of romantic relationships. Her work draws on peer-reviewed research
            but is written to be immediately useful rather than academically distant.
          </p>
          <p>
            Her flagship title, <em>Why He Pulls Away: The Attachment Science That
            Explains Every Confusing Thing Men Do</em>, has helped thousands of women
            understand the avoidant attachment patterns that cause so much confusion
            and pain in relationships.
          </p>
          <p>
            Sophia's writing is characterised by its directness — she doesn't traffic
            in generalities or hollow affirmations. Every chapter answers a specific
            question with a specific, evidence-backed answer.
          </p>
        </div>

      </div>

      <div style="background:#1a1a2e;color:#fff;border-radius:10px;padding:32px;
                  margin-top:48px;text-align:center">
        <h2 style="color:#c9a84c;margin-bottom:8px">Our Promise</h2>
        <p style="color:#b0b8c8;max-width:560px;margin:0 auto 20px;line-height:1.7">
          Every book we publish is research-grounded, practically focused, and
          honestly priced. We don't publish filler. If a guide doesn't earn its
          place in your library, it doesn't get published.
        </p>
        <a href="./books.html" class="btn btn-gold" style="display:inline-block">
          Browse the Library &rarr;
        </a>
      </div>
    </div>
  </section>
</main>
"""
        + _footer()
        + "\n</body>\n</html>"
    )

    out = OUTPUT_DIR / "about.html"
    out.write_text(page, encoding="utf-8")
    logger.info("[website] about.html generated")
    return out


def generate_lead_magnet_pdf() -> None:
    """Generate the lead magnet PDF (idempotent — skips if already exists)."""
    pdf = OUTPUT_DIR / "downloads" / "5-signs-he-pulls-away.pdf"
    if pdf.exists():
        return
    try:
        from engines.marketing.email_list import generate_lead_magnet
        generate_lead_magnet()
    except Exception as exc:
        logger.warning("[website] Lead magnet PDF generation skipped: %s", exc)


# ── Sitemap ────────────────────────────────────────────────────────────────────

def generate_sitemap() -> Path:
    """Generate sitemap.xml listing all static pages and blog articles."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    base = SITEMAP_BASE.rstrip("/")
    static_pages = [
        (base + "/",           "1.0", "weekly"),
        (base + "/books.html", "0.9", "weekly"),
        (base + "/blog.html",  "0.8", "weekly"),
        (base + "/about.html", "0.5", "monthly"),
    ]

    urls = []
    for loc, priority, freq in static_pages:
        urls.append(
            f"  <url>\n"
            f"    <loc>{loc}</loc>\n"
            f"    <lastmod>{today}</lastmod>\n"
            f"    <changefreq>{freq}</changefreq>\n"
            f"    <priority>{priority}</priority>\n"
            f"  </url>"
        )

    for article_path in sorted(BLOG_DIR.glob("*.html")):
        slug = article_path.stem
        loc  = f"{base}/blog/{slug}.html"
        # Try to read lastmod from the file's datePublished schema if present
        lastmod = today
        try:
            import re as _re
            text = article_path.read_text(encoding="utf-8", errors="ignore")
            m = _re.search(r'"datePublished":\s*"(\d{4}-\d{2}-\d{2})"', text)
            if m:
                lastmod = m.group(1)
        except Exception:
            pass
        urls.append(
            f"  <url>\n"
            f"    <loc>{loc}</loc>\n"
            f"    <lastmod>{lastmod}</lastmod>\n"
            f"    <changefreq>monthly</changefreq>\n"
            f"    <priority>0.7</priority>\n"
            f"  </url>"
        )

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls)
        + "\n</urlset>\n"
    )

    out = OUTPUT_DIR / "sitemap.xml"
    out.write_text(xml, encoding="utf-8")
    logger.info("[website] sitemap.xml — %d URLs", len(urls))
    return out


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_all() -> list[Path]:
    """Generate the complete static website. Called by scheduler daily."""
    BLOG_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "downloads").mkdir(parents=True, exist_ok=True)
    generate_lead_magnet_pdf()
    paths = [
        generate_home(),
        generate_books(),
        generate_blog_index(),
        generate_about(),
        generate_sitemap(),
    ]
    logger.info("[website] Full site generated (%d pages)", len(paths))
    return paths


def generate() -> Path:
    """Backward-compatible entry point — generates all pages, returns index.html path."""
    pages = generate_all()
    return pages[0]


if __name__ == "__main__":
    import logging as _lg
    _lg.basicConfig(level=_lg.INFO)
    for p in generate_all():
        print(f"Generated: {p}")
